version: '3.9'

services:
  web:
    container_name: frontend
    image: nginx:1.23.2-alpine
    ports:
      - 8888:80
    volumes:
      - ./logs/nginx:/var/log/nginx/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/
    networks:
      - local_w

  php:
    container_name: backend
    image: php:fpm-alpine
    volumes:
      - ./logs/php:/var/log/php-fpm
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html/
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - local_w
networks:
  local_w:
    driver: bridge